#!/usr/bin/env python3
"""
MaTiSSe.py, Markdown To Impressive Scientific Slides — core build logic.

The CLI entry point is in matisse.cli; main() here is a thin shim so the
registered console-script "MaTiSSe.py = matisse.matisse:main" keeps working.
"""

import shutil

from .presentation import Presentation

__sample__ = r"""
---
metadata:
  - title: "Autogenerated Sample"
  - conference: "Very nice Conference"
  - date: "12th December 2012"
  - authors:
    - Stefano Zaghi
    - John Doe
  - authors_short:
    - S. Zaghi
    - J. Doe
  - affiliations:
    - University 1
    - University 2
  - affiliations_short:
    - Univ. 1
    - Univ. 2
---

# First Chapter

## First Section

### First Subsection

#### First Slide

##### A H5 heading

Lorem ipsum dolor sit amet...

##### Math

$$
x=\frac{-b\pm\sqrt{b^2-4ac}}{2a}
$$

$note
$content{Just a note enviroment}
$endnote

##### Unordered list

+ $authors
+ $title

##### Ordered list

1. $affiliations
1. $conference

# Second Chapter

## Second Section

### Second Subsection

#### Second Slide

$table
$caption{Just a table enviroment}
$content{
| Foo | Bar | Baz | Authors  | Title  |
|-----|-----|-----|----------|--------|
| 1   |  2  |  3  | $authors | $title |
| 2   |  3  |  4  |    /     |   /    |
| 3   |  4  |  5  |    /     |   /    |
| 4   |  5  |  6  |    /     |   /    |
}
$endtable
"""


def make_presentation(config, source, output):
    """Build the presentation and write it to *output*.

    Parameters
    ----------
    config : MatisseConfig
    source : str
        Markdown source string.
    output : str
        Output directory path.

    Returns
    -------
    str
        The parsed (include-resolved) source.
    """
    config.make_output_tree(output=output)
    if config.theme is not None:
        source = config.put_theme(source=source, output=output)
    presentation = Presentation()
    presentation.parse(config=config, source=source)
    presentation.save(config=config, output=output)
    if config.theme is not None:
        shutil.rmtree("theme-" + config.theme, ignore_errors=True)
    return source


def main():
    """CLI entry point — delegates to the Typer app in matisse.cli."""
    from .cli import main as _cli_main

    _cli_main()


if __name__ == "__main__":
    main()
